import React from "react";
import Head from "next/head";
import HeaderComponent from "../src/components/common/HeaderComponent";
import FooterComponent from "../src/components/common/FooterComponent";
import BedriftStartPage from "../src/components/bedrift/BedriftStartPage";
import ImageLayout from "../src/components/common/ImageLayout";
import styles from "../styles/Bedrift.module.css";

function bedrift() {
  return (
    <div>
      <Head>
        <title>IT Care AS -forenkler din digitale hverdag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageLayout>
        <HeaderComponent />
        <div className={styles.imgContainer}></div>
        <BedriftStartPage />
        <FooterComponent />
      </ImageLayout>
    </div>
  );
}

export default bedrift;
