import Head from "next/head";
import FooterComponent from "../src/components/common/FooterComponent";
import HeaderComponent from "../src/components/common/HeaderComponent";
import HomePage from "../src/components/homepage/HomePage";
import ImageSection from "../src/components/homepage/ImageSection";
import StartPageLayout from "../src/components/homepage/StartPageLayout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IT Care AS -forenkler din digitale hverdag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StartPageLayout>
        <HeaderComponent />
        <ImageSection />
        <HomePage />
        <FooterComponent />
      </StartPageLayout>
    </div>
  );
}
